#
# Created by Luo Yu on 2021/12/17.
# Copyright © 2021 Luo Yu. All rights reserved.
#

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '11.0'

def lypods
	pod 'LYCategory'
	pod 'LYFactAppCommon'
end

def bdpods
	pod 'LYModuleChat', :path => '../'
end

target 'LYModuleChat_Example' do
	
	lypods
	bdpods
	
end

# MODIFY PODS PROJECT,
# RESET PROJECT BUILD TARGET OS VERSION.
post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
				config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
			end
		end
	end
end
